[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  dashboard = true
  insecure = true

[ping]
  entryPoint = "web"

[log]
level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = true
  [providers.ecs]
    autoDiscoverClusters = true
